### ISSUE TITLE
Pip install -r requirements.txt fails on first attempt

### ISSUE THREAD

**Issue by FelixBenning** [scikit-tda/scikit-tda#15]
# Problem description

I wrote the following `requirements.txt`

```pip
Cython>=0.29.21
numpy>=1.19.2
scikit-tda>=0.0.3
```

The command `pip install -r requirements.txt` fails as it can not find the module Cython

```shell
Step 4/5 : RUN pip install -r  /tmp/requirements.txt
 ---> Running in 853ba8bd6142
Collecting Cython>=0.29.21
  Downloading Cython-0.29.21-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
Collecting numpy>=1.19.2
  Downloading numpy-1.19.2-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Collecting scikit-tda>=0.0.3
  Downloading scikit_tda-0.0.3-py3-none-any.whl (2.6 kB)
Collecting matplotlib
  Downloading matplotlib-3.3.2-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
Collecting ripser
  Downloading ripser-0.5.4.tar.gz (81 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4nort0ro/ripser/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4nort0ro/ripser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"'
, open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7jsjq948
         cwd: /tmp/pip-install-4nort0ro/ripser/
    Complete output (2 lines):
    You don't seem to have Cython installed. Please get a
    copy from www.cython.org or install it with `pip install Cython`
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install -r  /tmp/requirements.txt' returned a non-zero code: 1
```

If you install Cython first and *then* install scikit-tda no error is encountered. In this case running `pip install -r requirements.txt` also works as Cython is already installed in the second round.

Similarly numpy needs to be installed beforehand to avoid this error:

```shell
Building wheels for collected packages: umap-learn, ripser, hopcroftkarp
  Building wheel for umap-learn (setup.py): started
  Building wheel for umap-learn (setup.py): finished with status 'done'
  Created wheel for umap-learn: filename=umap_learn-0.4.6-py3-none-any.whl size=
67950 sha256=d02da08e28b24bc2ba921a3003f8a6a7b07b0d3f90c82fab0fb88e63447841ed
  Stored in directory: /root/.cache/pip/wheels/9c/18/d0/2bcf7df75d19c6ca6ff8097b
12abd4c46879e9a8275e93e651
  Building wheel for ripser (setup.py): started
  Building wheel for ripser (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.a
rgv[0] = '"'"'/tmp/pip-install-qfhqfl3z/ripser/setup.py'"'"'; __file__='"'"'/tmp
/pip-install-qfhqfl3z/ripser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', o
pen)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exe
c(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dj3r8y
ry
       cwd: /tmp/pip-install-qfhqfl3z/ripser/
  Complete output (37 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/ripser
  copying ripser/_version.py -> build/lib.linux-x86_64-3.8/ripser
  copying ripser/__init__.py -> build/lib.linux-x86_64-3.8/ripser
  copying ripser/ripser.py -> build/lib.linux-x86_64-3.8/ripser
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-qfhqfl3z/ripser/setup.py", line 80, in <module>
      setup(
    File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 1
53, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290
, in run
      self.run_command('build')
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-qfhqfl3z/ripser/setup.py", line 39, in run
      import numpy
```

# Workaround

Installing `scikit-tda` after installing those two dependencies works fine. So removing `scikit-tda` from the `requirements.txt` and executing `pip install scikit-tda>=0.0.3` afterwards works perfectly well.

# Dockerfile for reproduction

```Dockerfile
FROM python:3.8

RUN pip install --upgrade pip

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
```

**Comment by FelixBenning** [comment]
In both cases [ripser](https://github.com/scikit-tda/ripser.py) seems to be the problem

**Comment by FelixBenning** [comment]
Will probably be fixed by https://github.com/scikit-tda/ripser.py/pull/96

**Comment by catanzaromj** [comment]
Closing as outdated and the ripser issue is fixed.
